<html>
<head><meta charset="utf-8"><title>wasmtime / issue #10007 Calling `store.into_data()` after... · git-wasmtime · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/index.html">git-wasmtime</a></h2>
<h3>Topic: <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2310007.20Calling.20.60store.2Einto_data.28.29.60.20after.2E.2E.2E.html">wasmtime / issue #10007 Calling `store.into_data()` after...</a></h3>

<hr>

<base href="https://bytecodealliance.zulipchat.com">

<head><link href="https://bytecodealliance.github.io/zulip-archive/style.css" rel="stylesheet"></head>

<a name="493563046"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/225357-git-wasmtime/topic/wasmtime%20/%20issue%20%2310007%20Calling%20%60store.into_data%28%29%60%20after.../near/493563046" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Wasmtime GitHub notifications bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2310007.20Calling.20.60store.2Einto_data.28.29.60.20after.2E.2E.2E.html#493563046">(Jan 14 2025 at 11:22)</a>:</h4>
<p><a href="https://github.com/tomasol">tomasol</a> added the bug label to <a href="https://github.com/bytecodealliance/wasmtime/issues/10007">Issue #10007</a>.</p>



<a name="493563082"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/225357-git-wasmtime/topic/wasmtime%20/%20issue%20%2310007%20Calling%20%60store.into_data%28%29%60%20after.../near/493563082" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Wasmtime GitHub notifications bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2310007.20Calling.20.60store.2Einto_data.28.29.60.20after.2E.2E.2E.html#493563082">(Jan 14 2025 at 11:22)</a>:</h4>
<p>tomasol opened <a href="https://github.com/bytecodealliance/wasmtime/issues/10007">issue #10007</a>:</p>
<blockquote>
<p>Calling <code>store.into_data()</code> after an execution finishes will trigger a panic in this <a href="#narrow/channel/217126-wasmtime/topic/assertion.20failed.3A.20self.2Estacks.2Eis_empty.28.29">debug assertion</a> of the pooling allocator's <code>drop</code> method.</p>
<h3>Test Case</h3>
<p>This commit will trigger the bug in a test: <a href="https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19">https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19</a></p>
<h3>Steps to Reproduce</h3>
<div class="codehilite" data-code-language="Rust"><pre><span></span><code><span class="p">#</span><span class="w"> </span><span class="k">in</span><span class="w"> </span><span class="n">wasmtime</span><span class="w"> </span><span class="n">repo</span>
<span class="n">git</span><span class="w"> </span><span class="n">remote</span><span class="w"> </span><span class="n">add</span><span class="w"> </span><span class="n">temp</span><span class="w"> </span><span class="n">git</span><span class="o">@</span><span class="n">github</span><span class="p">.</span><span class="n">com</span><span class="p">:</span><span class="nc">tomasol</span><span class="o">/</span><span class="n">wasmtime</span><span class="p">.</span><span class="n">git</span>
<span class="n">git</span><span class="w"> </span><span class="n">fetch</span><span class="w"> </span><span class="n">temp</span>
<span class="n">git</span><span class="w"> </span><span class="n">checkout</span><span class="w"> </span><span class="n">temp</span><span class="o">/</span><span class="n">pooling</span><span class="o">-</span><span class="n">stacks</span><span class="o">-</span><span class="n">panic</span>
<span class="n">cargo</span><span class="w"> </span><span class="n">test</span><span class="w"> </span><span class="o">--</span><span class="w">  </span><span class="n">async_functions</span><span class="p">::</span><span class="n">async_host_func_with_pooling_stack</span>
</code></pre></div>
<h3>Expected Results</h3>
<p>I expect that calling <code>store.into_data()</code> after the execution is OK.</p>
<h3>Actual Results</h3>
<p>With debug assertions turned on, the destructor of the pooling allocator panics with:</p>
<div class="codehilite" data-code-language="Rust"><pre><span></span><code><span class="n">thread</span><span class="w"> </span><span class="o">'</span><span class="na">async_functions</span><span class="p">::</span><span class="n">async_host_func_with_pooling_stacks</span><span class="o">'</span><span class="w"> </span><span class="n">panicked</span><span class="w"> </span><span class="n">at</span><span class="w"> </span><span class="n">crates</span><span class="o">/</span><span class="n">wasmtime</span><span class="o">/</span><span class="n">src</span><span class="o">/</span><span class="n">runtime</span><span class="o">/</span><span class="n">vm</span><span class="o">/</span><span class="n">instance</span><span class="o">/</span><span class="n">allocator</span><span class="o">/</span><span class="n">pooling</span><span class="p">.</span><span class="n">rs</span><span class="p">:</span><span class="mi">319</span><span class="p">:</span><span class="mi">9</span><span class="p">:</span>
<span class="nc">assertion</span><span class="w"> </span><span class="n">failed</span><span class="p">:</span><span class="w"> </span><span class="nc">self</span><span class="p">.</span><span class="n">stacks</span><span class="p">.</span><span class="n">is_empty</span><span class="p">()</span>
</code></pre></div>
<h3>Versions and Environment</h3>
<p>Wasmtime version: 28. I did not see it before updating to 28.</p>
<p>Operating system: Linux</p>
<p>Architecture: x86<br>
</p>
</blockquote>



<a name="493563143"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/225357-git-wasmtime/topic/wasmtime%20/%20issue%20%2310007%20Calling%20%60store.into_data%28%29%60%20after.../near/493563143" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Wasmtime GitHub notifications bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2310007.20Calling.20.60store.2Einto_data.28.29.60.20after.2E.2E.2E.html#493563143">(Jan 14 2025 at 11:22)</a>:</h4>
<p>tomasol edited <a href="https://github.com/bytecodealliance/wasmtime/issues/10007">issue #10007</a>:</p>
<blockquote>
<p>Calling <code>store.into_data()</code> after an execution finishes will trigger a panic in this <a href="https://github.com/bytecodealliance/wasmtime/blob/release-28.0.0/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs#L319">debug assertion</a> of the pooling allocator's <code>drop</code> method.</p>
<h3>Test Case</h3>
<p>This commit will trigger the bug in a test: <a href="https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19">https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19</a></p>
<h3>Steps to Reproduce</h3>
<div class="codehilite" data-code-language="Rust"><pre><span></span><code><span class="p">#</span><span class="w"> </span><span class="k">in</span><span class="w"> </span><span class="n">wasmtime</span><span class="w"> </span><span class="n">repo</span>
<span class="n">git</span><span class="w"> </span><span class="n">remote</span><span class="w"> </span><span class="n">add</span><span class="w"> </span><span class="n">temp</span><span class="w"> </span><span class="n">git</span><span class="o">@</span><span class="n">github</span><span class="p">.</span><span class="n">com</span><span class="p">:</span><span class="nc">tomasol</span><span class="o">/</span><span class="n">wasmtime</span><span class="p">.</span><span class="n">git</span>
<span class="n">git</span><span class="w"> </span><span class="n">fetch</span><span class="w"> </span><span class="n">temp</span>
<span class="n">git</span><span class="w"> </span><span class="n">checkout</span><span class="w"> </span><span class="n">temp</span><span class="o">/</span><span class="n">pooling</span><span class="o">-</span><span class="n">stacks</span><span class="o">-</span><span class="n">panic</span>
<span class="n">cargo</span><span class="w"> </span><span class="n">test</span><span class="w"> </span><span class="o">--</span><span class="w">  </span><span class="n">async_functions</span><span class="p">::</span><span class="n">async_host_func_with_pooling_stack</span>
</code></pre></div>
<h3>Expected Results</h3>
<p>I expect that calling <code>store.into_data()</code> after the execution is OK.</p>
<h3>Actual Results</h3>
<p>With debug assertions turned on, the destructor of the pooling allocator panics with:</p>
<div class="codehilite" data-code-language="Rust"><pre><span></span><code><span class="n">thread</span><span class="w"> </span><span class="o">'</span><span class="na">async_functions</span><span class="p">::</span><span class="n">async_host_func_with_pooling_stacks</span><span class="o">'</span><span class="w"> </span><span class="n">panicked</span><span class="w"> </span><span class="n">at</span><span class="w"> </span><span class="n">crates</span><span class="o">/</span><span class="n">wasmtime</span><span class="o">/</span><span class="n">src</span><span class="o">/</span><span class="n">runtime</span><span class="o">/</span><span class="n">vm</span><span class="o">/</span><span class="n">instance</span><span class="o">/</span><span class="n">allocator</span><span class="o">/</span><span class="n">pooling</span><span class="p">.</span><span class="n">rs</span><span class="p">:</span><span class="mi">319</span><span class="p">:</span><span class="mi">9</span><span class="p">:</span>
<span class="nc">assertion</span><span class="w"> </span><span class="n">failed</span><span class="p">:</span><span class="w"> </span><span class="nc">self</span><span class="p">.</span><span class="n">stacks</span><span class="p">.</span><span class="n">is_empty</span><span class="p">()</span>
</code></pre></div>
<h3>Versions and Environment</h3>
<p>Wasmtime version: 28. I did not see it before updating to 28.</p>
<p>Operating system: Linux</p>
<p>Architecture: x86<br>
</p>
</blockquote>



<a name="493624437"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/225357-git-wasmtime/topic/wasmtime%20/%20issue%20%2310007%20Calling%20%60store.into_data%28%29%60%20after.../near/493624437" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Wasmtime GitHub notifications bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2310007.20Calling.20.60store.2Einto_data.28.29.60.20after.2E.2E.2E.html#493624437">(Jan 14 2025 at 16:34)</a>:</h4>
<p>alexcrichton <a href="https://github.com/bytecodealliance/wasmtime/issues/10007#issuecomment-2590486930">commented</a> on <a href="https://github.com/bytecodealliance/wasmtime/issues/10007">issue #10007</a>:</p>
<blockquote>
<p>Thanks for this! This is fixed in <a href="https://github.com/bytecodealliance/wasmtime/pull/10009">https://github.com/bytecodealliance/wasmtime/pull/10009</a> and I'll backport this to make a 28.0.1 release as well.</p>
</blockquote>



<a name="493655377"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/225357-git-wasmtime/topic/wasmtime%20/%20issue%20%2310007%20Calling%20%60store.into_data%28%29%60%20after.../near/493655377" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Wasmtime GitHub notifications bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20issue.20.2310007.20Calling.20.60store.2Einto_data.28.29.60.20after.2E.2E.2E.html#493655377">(Jan 14 2025 at 19:37)</a>:</h4>
<p>alexcrichton closed <a href="https://github.com/bytecodealliance/wasmtime/issues/10007">issue #10007</a>:</p>
<blockquote>
<p>Calling <code>store.into_data()</code> after an execution finishes will trigger a panic in this <a href="https://github.com/bytecodealliance/wasmtime/blob/release-28.0.0/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs#L319">debug assertion</a> of the pooling allocator's <code>drop</code> method.</p>
<h3>Test Case</h3>
<p>This commit will trigger the bug in a test: <a href="https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19">https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19</a></p>
<h3>Steps to Reproduce</h3>
<div class="codehilite" data-code-language="Rust"><pre><span></span><code><span class="p">#</span><span class="w"> </span><span class="k">in</span><span class="w"> </span><span class="n">wasmtime</span><span class="w"> </span><span class="n">repo</span>
<span class="n">git</span><span class="w"> </span><span class="n">remote</span><span class="w"> </span><span class="n">add</span><span class="w"> </span><span class="n">temp</span><span class="w"> </span><span class="n">git</span><span class="o">@</span><span class="n">github</span><span class="p">.</span><span class="n">com</span><span class="p">:</span><span class="nc">tomasol</span><span class="o">/</span><span class="n">wasmtime</span><span class="p">.</span><span class="n">git</span>
<span class="n">git</span><span class="w"> </span><span class="n">fetch</span><span class="w"> </span><span class="n">temp</span>
<span class="n">git</span><span class="w"> </span><span class="n">checkout</span><span class="w"> </span><span class="n">temp</span><span class="o">/</span><span class="n">pooling</span><span class="o">-</span><span class="n">stacks</span><span class="o">-</span><span class="n">panic</span>
<span class="n">cargo</span><span class="w"> </span><span class="n">test</span><span class="w"> </span><span class="o">--</span><span class="w">  </span><span class="n">async_functions</span><span class="p">::</span><span class="n">async_host_func_with_pooling_stack</span>
</code></pre></div>
<h3>Expected Results</h3>
<p>I expect that calling <code>store.into_data()</code> after the execution is OK.</p>
<h3>Actual Results</h3>
<p>With debug assertions turned on, the destructor of the pooling allocator panics with:</p>
<div class="codehilite" data-code-language="Rust"><pre><span></span><code><span class="n">thread</span><span class="w"> </span><span class="o">'</span><span class="na">async_functions</span><span class="p">::</span><span class="n">async_host_func_with_pooling_stacks</span><span class="o">'</span><span class="w"> </span><span class="n">panicked</span><span class="w"> </span><span class="n">at</span><span class="w"> </span><span class="n">crates</span><span class="o">/</span><span class="n">wasmtime</span><span class="o">/</span><span class="n">src</span><span class="o">/</span><span class="n">runtime</span><span class="o">/</span><span class="n">vm</span><span class="o">/</span><span class="n">instance</span><span class="o">/</span><span class="n">allocator</span><span class="o">/</span><span class="n">pooling</span><span class="p">.</span><span class="n">rs</span><span class="p">:</span><span class="mi">319</span><span class="p">:</span><span class="mi">9</span><span class="p">:</span>
<span class="nc">assertion</span><span class="w"> </span><span class="n">failed</span><span class="p">:</span><span class="w"> </span><span class="nc">self</span><span class="p">.</span><span class="n">stacks</span><span class="p">.</span><span class="n">is_empty</span><span class="p">()</span>
</code></pre></div>
<h3>Versions and Environment</h3>
<p>Wasmtime version: 28. I did not see it before updating to 28.</p>
<p>Operating system: Linux</p>
<p>Architecture: x86<br>
</p>
</blockquote>



<hr><p>Last updated: Jan 20 2025 at 06:04 UTC</p>
</html>