[
    {
        "content": "<p>cfallin <a href=\"https://github.com/bytecodealliance/wasmtime/issues/1159#issuecomment-1117991355\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/1159\">issue #1159</a>:</p>\n<blockquote>\n<p>This is an old issue that I think is \"working as expected\" (one needs to provide an external stack-probe function), so I will go ahead and close.</p>\n</blockquote>",
        "id": 281228688,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1651703207
    },
    {
        "content": "<p>cfallin closed <a href=\"https://github.com/bytecodealliance/wasmtime/issues/1159\">issue #1159</a>:</p>\n<blockquote>\n<ul>\n<li>What are the steps to reproduce the issue? Can you include a CLIF test case,<br>\n  ideally reduced with the <code>bugpoint</code> clif-util command?</li>\n</ul>\n<div class=\"codehilite\" data-code-language=\"clif\"><pre><span></span><code>function u0:0() -&gt; i32 system_v {\n    ss0 = explicit_slot 10000\n    ss1 = explicit_slot 10000\n\nebb0:\n    v0 = iconst.i32 0\n    return v0\n}\n</code></pre></div>\n<ul>\n<li>What do you expect to happen? What does actually happen? Does it panic, and<br>\n  if so, with which assertion?</li>\n</ul>\n<p>I expect this to compile and return 0. Instead I get a linker error:<br>\n<code>/usr/local/bin/ld: /tmp/.tmpK629Dc: in function `main':\nintcode.c:(.text.main+0xc): undefined reference to `__cranelift_probestack'</code></p>\n<ul>\n<li>Which Cranelift version / commit hash / branch are you using?</li>\n</ul>\n<p>Cranelift 0.49.0</p>\n<ul>\n<li>If relevant, can you include some extra information about your environment?<br>\nx86_64 Linux, Ubuntu 18.04 LTS, linking using GNU ld 2.32. I am using cranelift-faerie to emit object files.</li>\n</ul>\n</blockquote>",
        "id": 281228689,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1651703207
    }
]