[
    {
        "content": "<p><a href=\"https://github.com/tomasol\">tomasol</a> added the bug label to <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10007\">Issue #10007</a>.</p>",
        "id": 493563046,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1736853722
    },
    {
        "content": "<p>tomasol opened <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10007\">issue #10007</a>:</p>\n<blockquote>\n<p>Calling <code>store.into_data()</code> after an execution finishes will trigger a panic in this <a href=\"#narrow/channel/217126-wasmtime/topic/assertion.20failed.3A.20self.2Estacks.2Eis_empty.28.29\">debug assertion</a> of the pooling allocator's <code>drop</code> method.</p>\n<h3>Test Case</h3>\n<p>This commit will trigger the bug in a test: <a href=\"https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19\">https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19</a></p>\n<h3>Steps to Reproduce</h3>\n<div class=\"codehilite\" data-code-language=\"Rust\"><pre><span></span><code><span class=\"p\">#</span><span class=\"w\"> </span><span class=\"k\">in</span><span class=\"w\"> </span><span class=\"n\">wasmtime</span><span class=\"w\"> </span><span class=\"n\">repo</span>\n<span class=\"n\">git</span><span class=\"w\"> </span><span class=\"n\">remote</span><span class=\"w\"> </span><span class=\"n\">add</span><span class=\"w\"> </span><span class=\"n\">temp</span><span class=\"w\"> </span><span class=\"n\">git</span><span class=\"o\">@</span><span class=\"n\">github</span><span class=\"p\">.</span><span class=\"n\">com</span><span class=\"p\">:</span><span class=\"nc\">tomasol</span><span class=\"o\">/</span><span class=\"n\">wasmtime</span><span class=\"p\">.</span><span class=\"n\">git</span>\n<span class=\"n\">git</span><span class=\"w\"> </span><span class=\"n\">fetch</span><span class=\"w\"> </span><span class=\"n\">temp</span>\n<span class=\"n\">git</span><span class=\"w\"> </span><span class=\"n\">checkout</span><span class=\"w\"> </span><span class=\"n\">temp</span><span class=\"o\">/</span><span class=\"n\">pooling</span><span class=\"o\">-</span><span class=\"n\">stacks</span><span class=\"o\">-</span><span class=\"n\">panic</span>\n<span class=\"n\">cargo</span><span class=\"w\"> </span><span class=\"n\">test</span><span class=\"w\"> </span><span class=\"o\">--</span><span class=\"w\">  </span><span class=\"n\">async_functions</span><span class=\"p\">::</span><span class=\"n\">async_host_func_with_pooling_stack</span>\n</code></pre></div>\n<h3>Expected Results</h3>\n<p>I expect that calling <code>store.into_data()</code> after the execution is OK.</p>\n<h3>Actual Results</h3>\n<p>With debug assertions turned on, the destructor of the pooling allocator panics with:</p>\n<div class=\"codehilite\" data-code-language=\"Rust\"><pre><span></span><code><span class=\"n\">thread</span><span class=\"w\"> </span><span class=\"o\">'</span><span class=\"na\">async_functions</span><span class=\"p\">::</span><span class=\"n\">async_host_func_with_pooling_stacks</span><span class=\"o\">'</span><span class=\"w\"> </span><span class=\"n\">panicked</span><span class=\"w\"> </span><span class=\"n\">at</span><span class=\"w\"> </span><span class=\"n\">crates</span><span class=\"o\">/</span><span class=\"n\">wasmtime</span><span class=\"o\">/</span><span class=\"n\">src</span><span class=\"o\">/</span><span class=\"n\">runtime</span><span class=\"o\">/</span><span class=\"n\">vm</span><span class=\"o\">/</span><span class=\"n\">instance</span><span class=\"o\">/</span><span class=\"n\">allocator</span><span class=\"o\">/</span><span class=\"n\">pooling</span><span class=\"p\">.</span><span class=\"n\">rs</span><span class=\"p\">:</span><span class=\"mi\">319</span><span class=\"p\">:</span><span class=\"mi\">9</span><span class=\"p\">:</span>\n<span class=\"nc\">assertion</span><span class=\"w\"> </span><span class=\"n\">failed</span><span class=\"p\">:</span><span class=\"w\"> </span><span class=\"nc\">self</span><span class=\"p\">.</span><span class=\"n\">stacks</span><span class=\"p\">.</span><span class=\"n\">is_empty</span><span class=\"p\">()</span>\n</code></pre></div>\n<h3>Versions and Environment</h3>\n<p>Wasmtime version: 28. I did not see it before updating to 28.</p>\n<p>Operating system: Linux</p>\n<p>Architecture: x86<br>\n</p>\n</blockquote>",
        "id": 493563082,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1736853723
    },
    {
        "content": "<p>tomasol edited <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10007\">issue #10007</a>:</p>\n<blockquote>\n<p>Calling <code>store.into_data()</code> after an execution finishes will trigger a panic in this <a href=\"https://github.com/bytecodealliance/wasmtime/blob/release-28.0.0/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs#L319\">debug assertion</a> of the pooling allocator's <code>drop</code> method.</p>\n<h3>Test Case</h3>\n<p>This commit will trigger the bug in a test: <a href=\"https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19\">https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19</a></p>\n<h3>Steps to Reproduce</h3>\n<div class=\"codehilite\" data-code-language=\"Rust\"><pre><span></span><code><span class=\"p\">#</span><span class=\"w\"> </span><span class=\"k\">in</span><span class=\"w\"> </span><span class=\"n\">wasmtime</span><span class=\"w\"> </span><span class=\"n\">repo</span>\n<span class=\"n\">git</span><span class=\"w\"> </span><span class=\"n\">remote</span><span class=\"w\"> </span><span class=\"n\">add</span><span class=\"w\"> </span><span class=\"n\">temp</span><span class=\"w\"> </span><span class=\"n\">git</span><span class=\"o\">@</span><span class=\"n\">github</span><span class=\"p\">.</span><span class=\"n\">com</span><span class=\"p\">:</span><span class=\"nc\">tomasol</span><span class=\"o\">/</span><span class=\"n\">wasmtime</span><span class=\"p\">.</span><span class=\"n\">git</span>\n<span class=\"n\">git</span><span class=\"w\"> </span><span class=\"n\">fetch</span><span class=\"w\"> </span><span class=\"n\">temp</span>\n<span class=\"n\">git</span><span class=\"w\"> </span><span class=\"n\">checkout</span><span class=\"w\"> </span><span class=\"n\">temp</span><span class=\"o\">/</span><span class=\"n\">pooling</span><span class=\"o\">-</span><span class=\"n\">stacks</span><span class=\"o\">-</span><span class=\"n\">panic</span>\n<span class=\"n\">cargo</span><span class=\"w\"> </span><span class=\"n\">test</span><span class=\"w\"> </span><span class=\"o\">--</span><span class=\"w\">  </span><span class=\"n\">async_functions</span><span class=\"p\">::</span><span class=\"n\">async_host_func_with_pooling_stack</span>\n</code></pre></div>\n<h3>Expected Results</h3>\n<p>I expect that calling <code>store.into_data()</code> after the execution is OK.</p>\n<h3>Actual Results</h3>\n<p>With debug assertions turned on, the destructor of the pooling allocator panics with:</p>\n<div class=\"codehilite\" data-code-language=\"Rust\"><pre><span></span><code><span class=\"n\">thread</span><span class=\"w\"> </span><span class=\"o\">'</span><span class=\"na\">async_functions</span><span class=\"p\">::</span><span class=\"n\">async_host_func_with_pooling_stacks</span><span class=\"o\">'</span><span class=\"w\"> </span><span class=\"n\">panicked</span><span class=\"w\"> </span><span class=\"n\">at</span><span class=\"w\"> </span><span class=\"n\">crates</span><span class=\"o\">/</span><span class=\"n\">wasmtime</span><span class=\"o\">/</span><span class=\"n\">src</span><span class=\"o\">/</span><span class=\"n\">runtime</span><span class=\"o\">/</span><span class=\"n\">vm</span><span class=\"o\">/</span><span class=\"n\">instance</span><span class=\"o\">/</span><span class=\"n\">allocator</span><span class=\"o\">/</span><span class=\"n\">pooling</span><span class=\"p\">.</span><span class=\"n\">rs</span><span class=\"p\">:</span><span class=\"mi\">319</span><span class=\"p\">:</span><span class=\"mi\">9</span><span class=\"p\">:</span>\n<span class=\"nc\">assertion</span><span class=\"w\"> </span><span class=\"n\">failed</span><span class=\"p\">:</span><span class=\"w\"> </span><span class=\"nc\">self</span><span class=\"p\">.</span><span class=\"n\">stacks</span><span class=\"p\">.</span><span class=\"n\">is_empty</span><span class=\"p\">()</span>\n</code></pre></div>\n<h3>Versions and Environment</h3>\n<p>Wasmtime version: 28. I did not see it before updating to 28.</p>\n<p>Operating system: Linux</p>\n<p>Architecture: x86<br>\n</p>\n</blockquote>",
        "id": 493563143,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1736853752
    },
    {
        "content": "<p>alexcrichton <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10007#issuecomment-2590486930\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10007\">issue #10007</a>:</p>\n<blockquote>\n<p>Thanks for this! This is fixed in <a href=\"https://github.com/bytecodealliance/wasmtime/pull/10009\">https://github.com/bytecodealliance/wasmtime/pull/10009</a> and I'll backport this to make a 28.0.1 release as well.</p>\n</blockquote>",
        "id": 493624437,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1736872479
    },
    {
        "content": "<p>alexcrichton closed <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10007\">issue #10007</a>:</p>\n<blockquote>\n<p>Calling <code>store.into_data()</code> after an execution finishes will trigger a panic in this <a href=\"https://github.com/bytecodealliance/wasmtime/blob/release-28.0.0/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs#L319\">debug assertion</a> of the pooling allocator's <code>drop</code> method.</p>\n<h3>Test Case</h3>\n<p>This commit will trigger the bug in a test: <a href=\"https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19\">https://github.com/tomasol/wasmtime/commit/1d0b9c57bc60ddeb6d39195692df3f4b01525a19</a></p>\n<h3>Steps to Reproduce</h3>\n<div class=\"codehilite\" data-code-language=\"Rust\"><pre><span></span><code><span class=\"p\">#</span><span class=\"w\"> </span><span class=\"k\">in</span><span class=\"w\"> </span><span class=\"n\">wasmtime</span><span class=\"w\"> </span><span class=\"n\">repo</span>\n<span class=\"n\">git</span><span class=\"w\"> </span><span class=\"n\">remote</span><span class=\"w\"> </span><span class=\"n\">add</span><span class=\"w\"> </span><span class=\"n\">temp</span><span class=\"w\"> </span><span class=\"n\">git</span><span class=\"o\">@</span><span class=\"n\">github</span><span class=\"p\">.</span><span class=\"n\">com</span><span class=\"p\">:</span><span class=\"nc\">tomasol</span><span class=\"o\">/</span><span class=\"n\">wasmtime</span><span class=\"p\">.</span><span class=\"n\">git</span>\n<span class=\"n\">git</span><span class=\"w\"> </span><span class=\"n\">fetch</span><span class=\"w\"> </span><span class=\"n\">temp</span>\n<span class=\"n\">git</span><span class=\"w\"> </span><span class=\"n\">checkout</span><span class=\"w\"> </span><span class=\"n\">temp</span><span class=\"o\">/</span><span class=\"n\">pooling</span><span class=\"o\">-</span><span class=\"n\">stacks</span><span class=\"o\">-</span><span class=\"n\">panic</span>\n<span class=\"n\">cargo</span><span class=\"w\"> </span><span class=\"n\">test</span><span class=\"w\"> </span><span class=\"o\">--</span><span class=\"w\">  </span><span class=\"n\">async_functions</span><span class=\"p\">::</span><span class=\"n\">async_host_func_with_pooling_stack</span>\n</code></pre></div>\n<h3>Expected Results</h3>\n<p>I expect that calling <code>store.into_data()</code> after the execution is OK.</p>\n<h3>Actual Results</h3>\n<p>With debug assertions turned on, the destructor of the pooling allocator panics with:</p>\n<div class=\"codehilite\" data-code-language=\"Rust\"><pre><span></span><code><span class=\"n\">thread</span><span class=\"w\"> </span><span class=\"o\">'</span><span class=\"na\">async_functions</span><span class=\"p\">::</span><span class=\"n\">async_host_func_with_pooling_stacks</span><span class=\"o\">'</span><span class=\"w\"> </span><span class=\"n\">panicked</span><span class=\"w\"> </span><span class=\"n\">at</span><span class=\"w\"> </span><span class=\"n\">crates</span><span class=\"o\">/</span><span class=\"n\">wasmtime</span><span class=\"o\">/</span><span class=\"n\">src</span><span class=\"o\">/</span><span class=\"n\">runtime</span><span class=\"o\">/</span><span class=\"n\">vm</span><span class=\"o\">/</span><span class=\"n\">instance</span><span class=\"o\">/</span><span class=\"n\">allocator</span><span class=\"o\">/</span><span class=\"n\">pooling</span><span class=\"p\">.</span><span class=\"n\">rs</span><span class=\"p\">:</span><span class=\"mi\">319</span><span class=\"p\">:</span><span class=\"mi\">9</span><span class=\"p\">:</span>\n<span class=\"nc\">assertion</span><span class=\"w\"> </span><span class=\"n\">failed</span><span class=\"p\">:</span><span class=\"w\"> </span><span class=\"nc\">self</span><span class=\"p\">.</span><span class=\"n\">stacks</span><span class=\"p\">.</span><span class=\"n\">is_empty</span><span class=\"p\">()</span>\n</code></pre></div>\n<h3>Versions and Environment</h3>\n<p>Wasmtime version: 28. I did not see it before updating to 28.</p>\n<p>Operating system: Linux</p>\n<p>Architecture: x86<br>\n</p>\n</blockquote>",
        "id": 493655377,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1736883422
    }
]