[
    {
        "content": "<p>alexcrichton opened <a href=\"https://github.com/bytecodealliance/wasmtime/issues/2470\">Issue #2470</a>:</p>\n<blockquote>\n<p>Recently a merged PR <a href=\"https://github.com/bytecodealliance/wasmtime/runs/1489518375?check_suite_focus=true\">failed CI on master</a> but then the next commit passed, so I'm curious if this might be an accidental bug in the new x64 backend? The errors unfortunately aren't the easiest to decipher, but wanted to open an issue to ensure we didn't lose this!</p>\n<p>cc @abrown @jlb6740 </p>\n</blockquote>",
        "id": 218706043,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1607008317
    },
    {
        "content": "<p>cfallin <a href=\"https://github.com/bytecodealliance/wasmtime/issues/2470#issuecomment-738166321\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/2470\">Issue #2470</a>:</p>\n<blockquote>\n<p>Hmm, thanks for reporting -- I think the best thing to do would be to disable the failing tests for now (<code>simd_f32x4</code>, <code>simd_f32x4_arith</code>, <code>simd_f64x2_arith</code>, <code>simd_splat</code>, <code>simd_load</code> from #2432). @abrown and @jlb6740 it might be worth running under Valgrind to find uninitialized value uses; this feels like it could be such an issue. I'll create a PR to disable the tests for now.</p>\n</blockquote>",
        "id": 218727900,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1607016876
    },
    {
        "content": "<p>jlb6740 <a href=\"https://github.com/bytecodealliance/wasmtime/issues/2470#issuecomment-738177167\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/2470\">Issue #2470</a>:</p>\n<blockquote>\n<p>@cfallin hi yes .. this is tricky @abrown and I just talked about this. There is definitely something intermittent going on that seems to be occurring on those tests that use floating point ... so maybe affects tests that we've not seen failures in yet. I think @abrown was going to resurrect a pr to help print these values in a way that allows us to compare the expected output with the received output more cleanly but separately we were going to see if we can in a loop reproduce failures we've seen recently and running valgrind is definitely a great idea .. I will try that during investigation.</p>\n</blockquote>",
        "id": 218730303,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1607017995
    },
    {
        "content": "<p>jlb6740 edited a <a href=\"https://github.com/bytecodealliance/wasmtime/issues/2470#issuecomment-738177167\">comment</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/2470\">Issue #2470</a>:</p>\n<blockquote>\n<p>@alexcrichton @cfallin hi yes .. this is tricky @abrown and I just talked about this. There is definitely something intermittent going on that seems to be occurring on those tests that use floating point ... so maybe affects tests that we've not seen failures in yet. I think @abrown was going to resurrect a pr to help print these values in a way that allows us to compare the expected output with the received output more cleanly but separately we were going to see if we can in a loop reproduce failures we've seen recently and running valgrind is definitely a great idea .. I will try that during investigation.</p>\n</blockquote>",
        "id": 218730374,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1607018031
    },
    {
        "content": "<p>abrown <a href=\"https://github.com/bytecodealliance/wasmtime/issues/2470#issuecomment-738559868\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/2470\">Issue #2470</a>:</p>\n<blockquote>\n<p>Ok, I'm closing this in favor of <a href=\"https://github.com/bytecodealliance/wasmtime/issues/2432\">https://github.com/bytecodealliance/wasmtime/issues/2432</a>; lets make that the main tracking issue for these failures.</p>\n</blockquote>",
        "id": 218793715,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1607056713
    },
    {
        "content": "<p>abrown closed <a href=\"https://github.com/bytecodealliance/wasmtime/issues/2470\">Issue #2470</a>:</p>\n<blockquote>\n<p>Recently a merged PR <a href=\"https://github.com/bytecodealliance/wasmtime/runs/1489518375?check_suite_focus=true\">failed CI on master</a> but then the next commit passed, so I'm curious if this might be an accidental bug in the new x64 backend? The errors unfortunately aren't the easiest to decipher, but wanted to open an issue to ensure we didn't lose this!</p>\n<p>cc @abrown @jlb6740 </p>\n</blockquote>",
        "id": 218793716,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1607056713
    }
]