[
    {
        "content": "<p>alexcrichton <a href=\"https://github.com/bytecodealliance/wasmtime/pull/5871#issuecomment-1442525983\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/pull/5871\">issue #5871</a>:</p>\n<blockquote>\n<p>This was uncovered by <a href=\"https://github.com/bytecodealliance/wasmtime/actions/runs/4256772626/jobs/7406079398\">this failing test run</a></p>\n</blockquote>",
        "id": 336356712,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1677192077
    },
    {
        "content": "<p>alexcrichton <a href=\"https://github.com/bytecodealliance/wasmtime/pull/5871#issuecomment-1442526453\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/pull/5871\">issue #5871</a>:</p>\n<blockquote>\n<p>We also didn't find this earlier since nothing in the test suite presumably exercises wait-with-timeout until <a href=\"https://github.com/bytecodealliance/wasmtime/pull/5858\">https://github.com/bytecodealliance/wasmtime/pull/5858</a> was merged.</p>\n</blockquote>",
        "id": 336356782,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1677192115
    }
]