[
    {
        "content": "<p>After updating to wasmtime 28 I see a panic with the message above when shutting down wasmtime: <a href=\"https://github.com/bytecodealliance/wasmtime/blob/release-28.0.0/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs#L319\">pooling.rs#L319</a><br>\nIs there a cleanup I have to perform when using the pooling allocator?</p>\n<div class=\"message_embed\"><a class=\"message_embed_image\" href=\"https://github.com/bytecodealliance/wasmtime/blob/release-28.0.0/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs#L319\" style=\"background-image: url(&quot;https://uploads.zulipusercontent.net/bdc75718a7905befa63577501295803c56017d2d/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f623639353461646566373834396538353638393336383766623863326337303036306132653066373564663965643337613161383265646530366437333737342f62797465636f6465616c6c69616e63652f7761736d74696d65&quot;)\"></a><div class=\"data-container\"><div class=\"message_embed_title\"><a href=\"https://github.com/bytecodealliance/wasmtime/blob/release-28.0.0/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs#L319\" title=\"wasmtime/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs at release-28.0.0 · bytecodealliance/wasmtime\">wasmtime/crates/wasmtime/src/runtime/vm/instance/allocator/pooling.rs at release-28.0.0 · bytecodealliance/wasmtime</a></div><div class=\"message_embed_description\">A lightweight WebAssembly runtime that is fast, secure, and standards-compliant - bytecodealliance/wasmtime</div></div></div>",
        "id": 493430639,
        "sender_full_name": "Tomas Olvecky",
        "timestamp": 1736796463
    },
    {
        "content": "<p>Hm that may indicate a bug because nothing about that should have changed. You're not <code>mem::forget</code>-ing anything are you?</p>",
        "id": 493431208,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1736796657
    },
    {
        "content": "<p>Nope. If I start the server and perform the graceful shutdown without running any executions, the panic won't appear.</p>",
        "id": 493441188,
        "sender_full_name": "Tomas Olvecky",
        "timestamp": 1736799915
    },
    {
        "content": "<p>Hm ok, how easy would it be to either reduce this to something you can share or share reproduction steps?</p>",
        "id": 493444548,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1736800987
    },
    {
        "content": "<p>I've managed to reproduce the issue in the wasmtime repo, created an issue for it <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10007\">here</a></p>\n<div class=\"message_embed\"><a class=\"message_embed_image\" href=\"https://github.com/bytecodealliance/wasmtime/issues/10007\" style=\"background-image: url(&quot;https://uploads.zulipusercontent.net/77af8e86f3d9c52175ed3afe316c21b0d329cf04/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f373364336334323631653665633763386639646461323361316562663239303463353037343636616563616539633665383066623538383534373739363737652f62797465636f6465616c6c69616e63652f7761736d74696d652f6973737565732f3130303037&quot;)\"></a><div class=\"data-container\"><div class=\"message_embed_title\"><a href=\"https://github.com/bytecodealliance/wasmtime/issues/10007\" title=\"Calling `store.into_data()` after an execution triggers a debug assertion failure in `drop` of the pooling allocator · Issue #10007 · bytecodealliance/wasmtime\">Calling `store.into_data()` after an execution triggers a debug assertion failure in `drop` of the pooling allocator · Issue #10007 · bytecodealliance/wasmtime</a></div><div class=\"message_embed_description\">Calling store.into_data() after an execution finishes will trigger a panic in this debug assertion of the pooling allocator's drop method. Test Case This commit will trigger the bug in a test: toma...</div></div></div>",
        "id": 493563266,
        "sender_full_name": "Tomas Olvecky",
        "timestamp": 1736853799
    },
    {
        "content": "<p>thanks!</p>",
        "id": 493611220,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1736868742
    }
]