<html>
<head><meta charset="utf-8"><title>Throwing exceptions from JS imports · jco · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/index.html">jco</a></h2>
<h3>Topic: <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html">Throwing exceptions from JS imports</a></h3>

<hr>

<base href="https://bytecodealliance.zulipchat.com">

<head><link href="https://bytecodealliance.github.io/zulip-archive/style.css" rel="stylesheet"></head>

<a name="427750855"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427750855" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Mart <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427750855">(Mar 19 2024 at 15:31)</a>:</h4>
<p>In jco transpiled components, when an imported function returns a result&lt;&gt; type, the generated trampoline function is wrapped in try/catch. This means if my import is filled with some js that throws an exception, it is caught:</p>
<div class="codehilite" data-code-language="Rust"><pre><span></span><code><span class="kr">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="n">ret</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="p">{</span><span class="w"> </span><span class="n">tag</span>: <span class="o">'</span><span class="na">ok</span><span class="o">'</span><span class="p">,</span><span class="w"> </span><span class="n">val</span>: <span class="nc">importedFunc</span><span class="p">(</span><span class="n">result0</span><span class="p">)};</span>
<span class="p">}</span><span class="w"> </span><span class="n">catch</span><span class="w"> </span><span class="p">(</span><span class="n">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="n">ret</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="p">{</span><span class="w"> </span><span class="n">tag</span>: <span class="o">'</span><span class="na">err</span><span class="o">'</span><span class="p">,</span><span class="w"> </span><span class="n">val</span>: <span class="nc">getErrorPayload</span><span class="p">(</span><span class="n">e</span><span class="p">)</span><span class="w"> </span><span class="p">};</span><span class="w">  </span><span class="c1">// &lt;--- Thrown exception caught. `Val` has useful information.</span>
<span class="p">}</span>
</code></pre></div>
<p>But if the shape of the thrown object is not of the expected Err variant type, then a new generic TypeError is rethrown after the deserialization fails, which makes sense, but it masks the information about what was actually thrown, and my catch handler outside the call to the wasm doesn't get the originally thrown payload.</p>
<p>I think that the originally thrown object should be attached to the thrown TypeError object. This would allow external parsers to deal with the object that was actually thrown by the imported function.</p>



<a name="427754907"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427754907" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Mart <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427754907">(Mar 19 2024 at 15:48)</a>:</h4>
<p>Some other return types do not have the generated exception handling code, and therefore anything thrown from the import is directly propagated to the caller. I'm not sure which other types besides Result&lt;ok, err&gt; result in automatic exception handling code being generated.</p>
<p>I suppose the generic form of this request is: <br>
All exceptions thrown from an import function should be propagated to the caller, in some way, even if it looks different depending on the expected return type of the import. <br>
To my eye, the only exception to this should be when the thrown object exactly fits the shape of the expected Err variant of a result, in which case it can be internally handled by the wasm (which is already working).</p>



<a name="427757636"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427757636" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Guy Bedford <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427757636">(Mar 19 2024 at 15:59)</a>:</h4>
<p>good point, I've posted <a href="https://github.com/bytecodealliance/jco/issues/405">https://github.com/bytecodealliance/jco/issues/405</a> to track</p>
<div class="message_embed"><a class="message_embed_image" href="https://github.com/bytecodealliance/jco/issues/405" style="background-image: url(https\:\/\/uploads\.zulipusercontent\.net\/54fae1802ea83a684d8065276e8f0be2efaaba13\/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f363463356465343064376661613661633161316339306336363335353533303463633137643832613766313535306162313032336166646466643238343862632f62797465636f6465616c6c69616e63652f6a636f2f6973737565732f343035)"></a><div class="data-container"><div class="message_embed_title"><a href="https://github.com/bytecodealliance/jco/issues/405" title="Non-conformant exceptions should unwrap as traps · Issue #405 · bytecodealliance/jco">Non-conformant exceptions should unwrap as traps · Issue #405 · bytecodealliance/jco</a></div><div class="message_embed_description">Rather than having a coercing getErrorPayload, if the error is a real JS error it should be rethrown.</div></div></div>



<a name="427799633"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427799633" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Mart <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427799633">(Mar 19 2024 at 19:45)</a>:</h4>
<p><span class="user-mention" data-user-id="553681">@Guy Bedford</span>  It actually strikes me as slightly odd that returning the error variant from within a component causes JCO to throw a ComponentError. Shouldn't throw be for trapping? Returning an Err variant of the Result enum is a valid return value.</p>



<a name="427799904"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427799904" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Guy Bedford <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427799904">(Mar 19 2024 at 19:47)</a>:</h4>
<p><span class="user-mention" data-user-id="648387">@James Mart</span> errors are part of the component model. So my thinking is that traps should be used whenever the incorrect types are used - for both errors and normal values. I believe that gets us to the right kind of consistent behaviour here? That is, the bug is that errors of the wrong type should become traps. It's only conformant errors that get coerced into component model result errors. Throwing non-errors in JS is generally an anti-pattern so that this gap is open to us to use here.</p>



<a name="427801542"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427801542" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Mart <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427801542">(Mar 19 2024 at 19:57)</a>:</h4>
<p>I agree traps should be used when the incorrect types are used. But I'm no longer talking about the <code>TypeError</code>, I'm suggesting there's a <em>possible</em> second issue here. </p>
<p>When I run a component, it returns an Err variant (conformant). But JCO throws to represent to the caller that the Err variant was returned.</p>
<div class="codehilite" data-code-language="Rust"><pre><span></span><code><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="n">variant5</span><span class="p">.</span><span class="n">tag</span><span class="w"> </span><span class="o">===</span><span class="w"> </span><span class="o">'</span><span class="na">err</span><span class="o">'</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="n">throw</span><span class="w"> </span><span class="n">new</span><span class="w"> </span><span class="n">ComponentError</span><span class="p">(</span><span class="n">variant5</span><span class="p">.</span><span class="n">val</span><span class="p">);</span>
<span class="p">}</span>
</code></pre></div>
<p>I don't feel strongly about this, but it does strike me as somewhat odd to throw this, rather than simply returning an object with the shape of the Err variant, given that the wasm never trapped. It is simply a type of valid response. My discomfort may just be due to my lack of familiarity with idiomatic js.</p>



<a name="427802080"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427802080" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Guy Bedford <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427802080">(Mar 19 2024 at 20:00)</a>:</h4>
<p>being able to throw errors to JavaScript callers is beneficial, and handled by this top-level error interpretation scheme</p>



<a name="427802131"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427802131" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Guy Bedford <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427802131">(Mar 19 2024 at 20:00)</a>:</h4>
<p>since the goal for component model embeddings is to provide idiomatic usage in different language environments</p>



<a name="427802207"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427802207" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Guy Bedford <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427802207">(Mar 19 2024 at 20:01)</a>:</h4>
<p>that is - traps are errors which are non-conformant with any possible top-level result error type</p>



<a name="427802282"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427802282" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Guy Bedford <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427802282">(Mar 19 2024 at 20:01)</a>:</h4>
<p>this just describes the desired behaviour though - right now we are a bit too flexible in these cases per the previous issue you posted</p>



<a name="427802539"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427802539" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Mart <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427802539">(Mar 19 2024 at 20:03)</a>:</h4>
<p>In my case, it now look like (in pseudocode):</p>
<div class="codehilite" data-code-language="Rust"><pre><span></span><code><span class="kr">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">     </span><span class="kd">let</span><span class="w"> </span><span class="n">returnValue</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">execute</span><span class="p">(</span><span class="n">component</span><span class="p">);</span>
<span class="w">     </span><span class="c1">// process ok value</span>
<span class="p">}</span>
<span class="n">catch</span><span class="w"> </span><span class="p">(</span><span class="n">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="n">e</span><span class="w"> </span><span class="o">==</span><span class="w"> </span><span class="n">trap</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">         </span><span class="c1">// trap! unrecoverable error</span>
<span class="w">    </span><span class="p">}</span>
<span class="w">    </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="n">e</span><span class="w"> </span><span class="o">==</span><span class="w"> </span><span class="n">normal</span><span class="w"> </span><span class="n">error</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">        </span><span class="c1">// process error value</span>
<span class="w">    </span><span class="p">}</span>
<span class="p">}</span>
</code></pre></div>
<p>Rather than</p>
<div class="codehilite" data-code-language="Rust"><pre><span></span><code><span class="kr">try</span><span class="w"> </span><span class="p">{</span>
<span class="w">     </span><span class="kd">let</span><span class="w"> </span><span class="n">returnValue</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">execute</span><span class="p">(</span><span class="n">component</span><span class="p">);</span>
<span class="w">     </span><span class="k">if</span><span class="w"> </span><span class="nb">Ok</span><span class="p">(</span><span class="n">returnValue</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">          </span><span class="c1">// process ok value</span>
<span class="w">     </span><span class="p">}</span><span class="w"> </span><span class="k">else</span><span class="w"> </span><span class="k">if</span><span class="w"> </span><span class="nb">Err</span><span class="p">(</span><span class="n">returnValue</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">         </span><span class="c1">// process error value</span>
<span class="w">    </span><span class="p">}</span>
<span class="p">}</span>
<span class="n">catch</span><span class="w"> </span><span class="p">(</span><span class="n">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span>
<span class="w">    </span><span class="c1">// Trap! unrecoverable error</span>
<span class="p">}</span>
</code></pre></div>



<a name="427803285"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427803285" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Mart <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427803285">(Mar 19 2024 at 20:09)</a>:</h4>
<p>My initial preference was for handling that looked more like the second code block above, since an Err variant is a valid response in my case. But I've understood from your response that the first block is correct &amp; idiomatic.</p>



<a name="427805064"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/409526-jco/topic/Throwing%20exceptions%20from%20JS%20imports/near/427805064" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Guy Bedford <a href="https://bytecodealliance.github.io/zulip-archive/stream/409526-jco/topic/Throwing.20exceptions.20from.20JS.20imports.html#427805064">(Mar 19 2024 at 20:21)</a>:</h4>
<p>Yes, that is the current design for idiomatic JS bindgen. You could do the explicit normal error checks before the trap checks since they will have the known shapes?</p>



<hr><p>Last updated: Jan 20 2025 at 06:04 UTC</p>
</html>