[
    {
        "content": "<p>Hi all - I'm currently working on a small example where I create a function, and then create a second function and try to call the first. I've tried a few variations of this, but I can't seem to get any of them to work. Here's the current one I have, if someone is up for a (hopefully quick) debugging session: <a href=\"https://gist.github.com/jntrnr/bd5d3b0fbe0e9dc8ea0f04c1d0930689\">https://gist.github.com/jntrnr/bd5d3b0fbe0e9dc8ea0f04c1d0930689</a></p>\n<p>The error I'm getting is:</p>\n<div class=\"codehilite\" data-code-language=\"Rust\"><pre><span></span><code><span class=\"n\">thread</span><span class=\"w\"> </span><span class=\"o\">'</span><span class=\"na\">main</span><span class=\"o\">'</span><span class=\"w\"> </span><span class=\"n\">panicked</span><span class=\"w\"> </span><span class=\"n\">at</span><span class=\"w\"> </span><span class=\"o\">'</span><span class=\"na\">index</span><span class=\"w\"> </span><span class=\"n\">out</span><span class=\"w\"> </span><span class=\"n\">of</span><span class=\"w\"> </span><span class=\"n\">bounds</span>: <span class=\"nc\">the</span><span class=\"w\"> </span><span class=\"n\">len</span><span class=\"w\"> </span><span class=\"n\">is</span><span class=\"w\"> </span><span class=\"mi\">0</span><span class=\"w\"> </span><span class=\"n\">but</span><span class=\"w\"> </span><span class=\"n\">the</span><span class=\"w\"> </span><span class=\"n\">index</span><span class=\"w\"> </span><span class=\"n\">is</span><span class=\"w\"> </span><span class=\"mi\">0</span><span class=\"o\">'</span><span class=\"p\">,</span><span class=\"w\"> </span><span class=\"o\">/</span><span class=\"n\">Users</span><span class=\"o\">/</span><span class=\"n\">jt</span><span class=\"o\">/</span><span class=\"p\">.</span><span class=\"n\">cargo</span><span class=\"o\">/</span><span class=\"n\">registry</span><span class=\"o\">/</span><span class=\"n\">src</span><span class=\"o\">/</span><span class=\"n\">github</span><span class=\"p\">.</span><span class=\"n\">com</span><span class=\"o\">-</span><span class=\"mi\">1</span><span class=\"n\">ecc6299db9ec823</span><span class=\"o\">/</span><span class=\"n\">cranelift</span><span class=\"o\">-</span><span class=\"n\">codegen</span><span class=\"o\">-</span><span class=\"mf\">0.93.0</span><span class=\"o\">/</span><span class=\"n\">src</span><span class=\"o\">/</span><span class=\"n\">ir</span><span class=\"o\">/</span><span class=\"n\">dfg</span><span class=\"p\">.</span><span class=\"n\">rs</span>:<span class=\"mi\">955</span>:<span class=\"mi\">44</span>\n<span class=\"n\">stack</span><span class=\"w\"> </span><span class=\"n\">backtrace</span>:\n</code></pre></div>\n<p>on the line that builds the call itself</p>\n<div class=\"message_embed\"><a class=\"message_embed_image\" href=\"https://gist.github.com/jntrnr/bd5d3b0fbe0e9dc8ea0f04c1d0930689\" style=\"background-image: url(https\\:\\/\\/uploads\\.zulipusercontent\\.net\\/2aafd906f69f8f71c7544060163ba3e419b173e8\\/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67)\"></a><div class=\"data-container\"><div class=\"message_embed_title\"><a href=\"https://gist.github.com/jntrnr/bd5d3b0fbe0e9dc8ea0f04c1d0930689\" title=\"cranelift_fn_example.rs\">cranelift_fn_example.rs</a></div><div class=\"message_embed_description\">GitHub Gist: instantly share code, notes, and snippets.</div></div></div>",
        "id": 338239910,
        "sender_full_name": "JT",
        "timestamp": 1677474303
    },
    {
        "content": "<p>The result of declare_func_in_func is only valid within a single function. You are calling it on the first function, but then using it on the second function.</p>",
        "id": 338271436,
        "sender_full_name": "bjorn3",
        "timestamp": 1677488933
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"264278\">bjorn3</span> <a href=\"#narrow/stream/217117-cranelift/topic/Calling.20between.20functions/near/338271436\">said</a>:</p>\n<blockquote>\n<p>The result of declare_func_in_func is only valid within a single function. You are calling it on the first function, but then using it on the second function.</p>\n</blockquote>\n<p>that makes sense. Is there a preferred way of doing what I'm trying to do?</p>",
        "id": 338271556,
        "sender_full_name": "JT",
        "timestamp": 1677488976
    },
    {
        "content": "<p>(deleted)</p>",
        "id": 338271625,
        "sender_full_name": "bjorn3",
        "timestamp": 1677488997
    },
    {
        "content": "<p>Call it after clear_context.</p>",
        "id": 338271775,
        "sender_full_name": "bjorn3",
        "timestamp": 1677489040
    },
    {
        "content": "<p>You could use it right before inserting the call instruction for example.</p>",
        "id": 338271949,
        "sender_full_name": "bjorn3",
        "timestamp": 1677489097
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"264278\">@bjorn3</span> that did it, I think. Thanks for the help!</p>",
        "id": 338273476,
        "sender_full_name": "JT",
        "timestamp": 1677489594
    }
]