[
    {
        "content": "<p>The only way for your example <code>add</code> function to fail - even if called asynchronously - is for it to trap.</p>",
        "id": 483344071,
        "sender_full_name": "Lann Martin",
        "timestamp": 1732046812
    },
    {
        "content": "<p>Ah, okay thanks. And also if C# or JS exception happens in the implementation of add, generated binding needs to trap. My problem A is also solved.</p>",
        "id": 483344669,
        "sender_full_name": "Pavel Šavara",
        "timestamp": 1732047022
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"471788\">Pavel Šavara</span> has marked this topic as resolved.</p>",
        "id": 483344829,
        "sender_full_name": "Notification Bot",
        "timestamp": 1732047090
    }
]